# Generated by Django 4.2 on 2023-12-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='memeber',
            new_name='members',
        ),
    ]
