# Generated by Django 4.2 on 2023-12-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='media/picture.jpg', upload_to='media/picture/')),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('slogan', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('cur_add', models.CharField(blank=True, max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('bank_details', models.CharField(blank=True, max_length=500)),
                ('fam_post_no', models.IntegerField(default=0)),
                ('org_post_no', models.IntegerField(default=0)),
                ('kind', models.CharField(blank=True, max_length=100)),
                ('reported', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('promote', models.BooleanField(blank=True, default=False)),
                ('restriction_hits', models.IntegerField(default=0)),
                ('restricted', models.BooleanField(blank=True, default=False)),
                ('admin_message', models.TextField(blank=True)),
                ('email_notif', models.BooleanField(blank=True, default=False)),
                ('cat', models.CharField(blank=True, default='General', max_length=200)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='vpvc_creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvc_verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Vpvc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VerifyPVC', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.ImageField(blank=True, null=True, upload_to='idcard')),
                ('UserVerified', models.BooleanField(default=False)),
                ('Vuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VerifyUser', to='profiles.profile')),
            ],
        ),
    ]
